#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/daniel/anaconda3"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/daniel/anaconda3/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/daniel/repos/pyDentate/mechs_7-6/x86_64/.libs/libnrnmech.so" "$@"
